from tkinter import*
########birinci pencere####
window=Tk()
window.title("pizza menüsü")
window.configure(bg="orange")
window.geometry("400x200")
mb=  Menubutton ( window, text="pizza menüsü", relief=RAISED )
mb.grid()
mb.menu =  Menu ( mb, tearoff = 0 )
mb["menu"] =  mb.menu
var1 = IntVar()
var2 = IntVar()
var3 = IntVar()
var4 = IntVar()
mb.menu.add_checkbutton ( label="klasik pizza ",variable=var1 )
mb.menu.add_checkbutton ( label="margarita pizza",variable=var2 )
mb.menu.add_checkbutton ( label="türk pizza",variable=var3 )
mb.menu.add_checkbutton ( label="sade pizza",variable=var4 )
mb.pack()
window.mainloop()
######ikinci pencere######
window1=Tk()
window1.title("malzeme menüsü")
window1.configure(bg="yellow")
window1.geometry("400x200")
checkbox= Checkbutton(window1,text="zeytin").grid(row=0)
checkbox2= Checkbutton(window1,text="mantar").grid(row=1)
checkbox3= Checkbutton(window1,text="fesleğen").grid(row=2)
window1.mainloop()
######üçüncü pencere########
window2=Tk()
window2.title("kullanıcı bilgileri")
window2.configure(bg="aqua")
window2.geometry("400x200")
L1 = Label(window2, text="isminiz")
L1.place(x=75, y=15)
E1 = Entry(window2, width=25)
E1.place(x=77,y=45)
L2 = Label(window2, text="Şifre")
L2.place(x=75, y=80)

E2 = Entry(window2, textvariable=StringVar(),show='*', width=25)
E2.place(x=77, y=110)
window2.mainloop()